---
booktitle: Proceedings of the Fifth Machine Learning for Health Symposium
shortname: ML4H
year: '2025'
volume: '297'
start: &1 2025-12-13
end: 2025-12-14
conference_number: '5'
published: 2026-05-05
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ml4h25
month: 0
cycles: false
bibtex_editor: Argaw, Peniel and Zhang, Haoran and Jabbour, Sarah and Chandak, Payal
  and Ji, Jerry and Mukherjee, Sumit and Salaudeen, Olawale and Chang, Trenton and
  Healey, Elizabeth and Gr{\"o}ger, Fabian and Adibi, Amin and Hegselmann, Stefan
  and Wild, Benjamin and Noori, Ayush
editor:
- given: Peniel
  family: Argaw
- given: Haoran
  family: Zhang
- given: Sarah
  family: Jabbour
- given: Payal
  family: Chandak
- given: Jerry
  family: Ji
- given: Sumit
  family: Mukherjee
- given: Olawale
  family: Salaudeen
- given: Trenton
  family: Chang
- given: Elizabeth
  family: Healey
- given: Fabian
  family: Gröger
- given: Amin
  family: Adibi
- given: Stefan
  family: Hegselmann
- given: Benjamin
  family: Wild
- given: Ayush
  family: Noori
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Fifth Machine Learning for Health Symposium
    Held in The Westin San Diego Gaslamp Quarter, San Diego, CA, USA on 13-14 December 2025

  Published as Volume 297 by the Proceedings of Machine Learning Research on 05 May 2026.

  Volume Edited by:
    Peniel Argaw
    Haoran Zhang
    Sarah Jabbour
    Payal Chandak
    Jerry Ji
    Sumit Mukherjee
    Olawale Salaudeen
    Trenton Chang
    Elizabeth Healey
    Fabian Gröger
    Amin Adibi
    Stefan Hegselmann
    Benjamin Wild
    Ayush Noori

  Series Editors:
    Neil D. Lawrence
date_str: 13--14 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v297"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v297
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v297
email: ''
conference:
  name: Machine Learning for Health Symposium
  url: https://ahli.cc/ml4h/
  location: The Westin San Diego Gaslamp Quarter, San Diego, CA, USA
  dates:
  - *1
  - 2025-12-14
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: v297_clean.bib
# Site settings
# Original source:  v297_clean.bib
